# Generated by Django 3.0.5 on 2020-12-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201207_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='partner',
        ),
    ]
