# Generated by Django 3.0.5 on 2020-12-07 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Discussion'),
            preserve_default=False,
        ),
    ]
