# Generated by Django 3.2.4 on 2021-06-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_appuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('affiliation', models.TextField(blank=True, null=True)),
                ('linkedin_account', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='appuser_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.teacher'),
        ),
    ]
