# Generated by Django 3.2.4 on 2021-06-30 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20210630_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='appuser_teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_appuser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
