# Generated by Django 3.2.4 on 2021-07-01 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20210630_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='ends_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='exam',
            name='starts_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='institute',
            name='code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_position',
            field=models.CharField(choices=[('B', 'BEFORE'), ('A', 'AFTER')], default='B', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(default=1)),
                ('exam_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.group')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.course'),
            preserve_default=False,
        ),
    ]
