# Generated by Django 3.2.4 on 2021-07-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20210701_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='avatar',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
