# Generated by Django 3.2.4 on 2021-07-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_institute_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
